[build]
  command = "npm run build"
  functions = "functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200